CREATE TABLE [Tv].[Cast]
(
	[CastShowId] NVARCHAR(50) NOT NULL,
	[Id] INT NOT NULL,
	[ShowId] INT NOT NULL,
	[Name] NVARCHAR(250) NOT NULL,
	[Birthday] NVARCHAR(10),
	CONSTRAINT [PK_Cast] PRIMARY KEY CLUSTERED (CastShowId),
	CONSTRAINT [FK_Cast_Shows] FOREIGN KEY ([ShowId]) REFERENCES [Tv].[Shows]([Id]) ON DELETE CASCADE
)